logging:
  version: 1
  disable_existing_loggers: False

  formatters:
    default:
      format: '%(asctime)s | %(levelname)10s | %(name)16s | %(message)s'

  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: default
      stream: ext://sys.stdout

    file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: default
      maxBytes: 20971520
      backupCount: 10
      encoding: utf8
      filename: word_count.log

  root:
      level: INFO
      handlers: [console, file]

